Repository BuildForSDG/wasteCoin-Backend, pull requests merged in 2020-06, with the labels that each got.

#11 added api endpoints and database models
  CustomCode/autentication.py
  CustomCode/fixed_var.py
  CustomCode/sms.py
  Procfile
  api/models.py
  api/urls.py
  api/views.py
  requirements.txt
  runtime.txt
Labels: enhancement

#14 added agent dashboard view
  api/views.py
Labels: enhancement

#16 added phone number validation
  api/views.py
Labels: bug

#17 Changed waste coin user-agent flow
  CustomCode/fixed_var.py
  api/models.py
  api/views.py
Labels: bug

#20 codacy issues on readme resolved
  README.md
Labels: documentation

#22 added contact us endpoint
  api/models.py
  api/views.py
Labels: enhancement

#24 update readme
  README.md
Labels: documentation
